#c.execute("""CREATE TABLE lineups (
#                ID integer,
#                GAMEID integer,
#                SEASONID integer,
#                SERIE TEXT,
#                VENUE TEXT,
#                AUDIENCE integer,
#                HOMETEAM TEXT,
#                AWAYTEAM TEXT,
#                TEAM TEXT,
#                GAMEDATE TEXT,
#                NUMBER integer,
#                FORNAME TEXT,
#                SURNAME TEXT,
#                POSITION TEXT,
#                START_PLAYER integer,
#                GOALS integer,
#                PPGOALS integer,
#                SHGOALS integer,
#                ASSISTS integer,
#                PLUS integer,
#                MINUS integer,
#                PENALTY integer,
#                INPOWERPLAT integer,
#                INBOXPLAY integer,
#                SHOTSAT integer,
#                SAVES integer,
#                SCORE integer,
#                FINALSCORE integer
#                )""")

#c.execute("""CREATE TABLE events (
#                ID integer,
#                GAMEID integer,
#                SEASONID integer,
#                VENUE TEXT,
#                AUDIENCE integer,
#                PERIOD integer,
#                TIME TEXT,
#                EVENT TEXT,
#                TEAM TEXT,
#                NUMBER TEXT,
#                PERSONNR TEXT,
#                FORNAME TEXT,
#                SURNAME TEXT,
#                EXTRA1 TEXT,
#                EXTRA2 TEXT)""")

#c.execute("""CREATE TABLE stats (
#                GAMEID integer,
#                GAMEDATE TEXT,
#                HOMETEAM TEXT,
#                AWAYTEAM TEXT,
#                HOMESCORE integer,
#                AWAYSCORE integer,
#                HOMESHOTS integer,
#                AWAYSHOTS integer,
#                HOMESAVES integer,
#                AWAYSAVES integer,
#                HOMEPENALTY integer,
#                AWAYPENALTY integer,
#                HSCORE1 integer,
#                HSCORE2 integer,
#                HSCORE3 integer,
#                HSCORE4 integer,
#                ASCORE1 integer,
#                ASCORE2 integer,
#                ASCORE3 integer,
#                ASCORE4 integer,
#                HSHOTS1 integer,
#                HSHOTS2 integer,
#                HSHOTS3 integer,
#                HSHOTS4 integer,
#                ASHOTS1 integer,
#                ASHOTS2 integer,
#                ASHOTS3 integer,
#                ASHOTS4 integer,
#                HSAVES1 integer,
#                HSAVES2 integer,
#                HSAVES3 integer,
#                HSAVES4 integer,
#                ASAVES1 integer,
#                ASAVES2 integer,
#                ASAVES3 integer,
#                ASAVES4 integer,
#                HPENALTY1 integer,
#                HPENALTY2 integer,
#                HPENALTY3 integer,
#                HPENALTY4 integer,
#                APENALTY1 integer,
#                APENALTY2 integer,
#                APENALTY3 integer,
#                APENALTY4 integer)""")

#c.execute("""CREATE TABLE refs (
#                GAMEID integer,
#                SEASONID integer,
#                VENUE TEXT,
#                AUDIENCE integer,
#                HOMETEAM TEXT,
#                AWAYTEAM TEXT,
#                REF1 TEXT,
#                REF2 TEXT,
#                LINE1 TEXT,
#                LINE2 TEXT)""")

#c.execute("""CREATE TABLE rosters (
#                SEASONID integer,
#                TEAM TEXT,
#                SERIE TEXT,
#                NUMBER integer,
#                SURNAME TEXT,
#                FORNAME TEXT,
#                PERSONNR TEXT,
#                POSITION TEXT,
#                HANDLE TEXT,
#                LENGHT integer,
#                WEIGHT integer,
#                LAST_UPDATE)""")

#c.execute("""CREATE TABLE pre_match_table (
#                SEASONID INTEGER,
#                SERIE INTEGER,
#                GAMEID INTEGER,
#                GAMEDATE TEXT,
#                TEAM TEXT,
#                TEAM_SHORT TEXT,
#                HOMETEAM TEXT,
#                AWAYTEAM TEXT,
#                VENUE TEXT,
#                MATCHES INTEGER,
#                WINS INTEGER,
#                OTWINS INTEGER,
#                OTLOSSES INTEGER,
#                LOSSES INTEGER,
#                SCORED INTEGER,
#                CONCEDED INTEGER,
#                SCORED_R INTEGER,
#                CONCEDED_R INTEGER,
#                POWERPLAY INTEGER,
#                BOXPLAY INTEGER,
#                WINS5 INTEGER,
#                POINTS5 INTEGER,
#                GOALS5 INTEGER,
#                CONS5 INTEGER,
#                PP5 INTEGER,
#                PPTREND5 INTEGER,
#                SHOTS5 INTEGER,
#                HWINS3 INTEGER,
#                HPOINTS3 INTEGER,
#                HGOALS3 INTEGER,
#                HCONS3 INTEGER,
#                LASTGAMEVENUE TEXT,
#                LASTGAMEHOMEGOAL INTEGER,
#                LASTGAMEAWAYGOAL INTEGER,
#                LAST5COMPETETION INTEGER,
#                WEIGHTEDFORM INTEGER,
#                DAYSSINCELASTGAME INTEGER,
#                SCHEME10DAYS INTEGER,
#                AVERAGESHOTS INTEGER,
#                POSITION INTEGER
#                )""")

#c.execute("""CREATE TABLE schedule (
#                SEASONID INTEGER,
#                SERIE INTEGER,
#                DATE TEXT,
#                HOMETEAM TEXT,
#                AWAYTEAM TEXT,
#                VENUE TEXT)""")


#c.execute("CREATE TABLE TEAMGAMES (SEASONID, SERIE, GAMEID, GAMEDATE, TEAM, HOMEAWAY, OPPONENT, OUTCOME, SCORE1, SCORE2, SHOTS1, SHOTS2, SAVES1, SAVES2, PENALTY1, PENALTY2, SCORE11, SCORE12, SCORE13, SCORE14, SCORE21, SCORE22, SCORE23, SCORE24, SHOTS11, SHOTS12, SHOTS13, SHOTS14, SHOTS21, SHOTS22, SHOTS23, SHOTS24)")


